this demonstrates use of python exceptions
